repos:
  - repo: https://github.com/crate-ci/typos
    rev: v1.32.0  # Latest version as confirmed
    hooks:
      - id: typos
        args: [--force-exclude, --config=./typos.toml]
        types: [text]
        stages: [commit]