[default.extend-words]
Hashi = "Hashi"
HashiCorp = "HashiCorp"
MyApp = "MyApp"
OpenAPIv3 = "OpenAPIv3"

[files]
extend-exclude = [
  "docs/legacy/*",
  "scripts/ignore_this.sh",
  "venv/*",
  ".env.local",
  ".gitignore",
  "mkdocs.yml",
  "requirements.txt"
]
