name: Check Typos

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  typos:
    name: Typos Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Ensure we have a clean checkout
          fetch-depth: 0
          clean: true
          
      # Clean workspace to ensure no cached files
      - name: Clean workspace
        run: |
          git clean -ffdx
          git reset --hard HEAD
          
      - name: Debug - Show current state
        run: |
          echo "=== Current branch and commit ==="
          git branch --show-current
          git log -1 --oneline
          echo ""
          echo "=== Git status ==="
          git status
          echo ""
          echo "=== Check if files exist ==="
          ls -la
          echo ""
          echo "=== Show .typos.toml if exists ==="
          if [ -f .typos.toml ]; then
            cat .typos.toml
          else
            echo ".typos.toml not found!"
          fi

      - name: Install latest typos
        run: |
          TY_POS_VERSION=$(curl -s https://api.github.com/repos/crate-ci/typos/releases/latest | jq -r .tag_name)
          ARCHIVE_NAME="typos-${TY_POS_VERSION}-x86_64-unknown-linux-musl.tar.gz"
          curl -LO "https://github.com/crate-ci/typos/releases/download/${TY_POS_VERSION}/${ARCHIVE_NAME}"
          tar -xzf "${ARCHIVE_NAME}"
          sudo mv typos /usr/local/bin/
          typos --version

      - name: Debug - List files that will be checked
        run: |
          echo "=== Files that typos will check ==="
          typos --config .typos.toml --files | head -20
          echo "... (showing first 20 files)"

      - name: Run typos
        run: typos --config .typos.toml