[default]
extend_words = [
  "MyApp",
  "OpenAPIv3",
  "Hashi",
  "HashiCorp"
  ]

[files]
extend_exclude = [
  "docs/legacy/*",
  "scripts/ignore_this.sh",
  "venv/*",
  ".env.local",
  ".gitignore",
  "mkdocs.yml",
  "requirements.txt"
  ]