name: Check Typos

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  typos:
    name: Typos Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install latest typos
        run: |
          TY_POS_VERSION=$(curl -s https://api.github.com/repos/crate-ci/typos/releases/latest | jq -r .tag_name)
          ARCHIVE_NAME="typos-${TY_POS_VERSION}-x86_64-unknown-linux-musl.tar.gz"
          curl -LO "https://github.com/crate-ci/typos/releases/download/${TY_POS_VERSION}/${ARCHIVE_NAME}"
          tar -xzf "${ARCHIVE_NAME}"
          sudo mv typos /usr/local/bin/
          typos --version

      - name: Run typos
        run: typos . --config .typos.toml  -v --files
