name: Check Typos

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  typos:
    name: Typos Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install typos
        run: |
          curl -LsSf https://github.com/crate-ci/typos/releases/latest/download/typos-$(uname -m)-unknown-linux-musl.tar.gz | tar xzf - -C /usr/local/bin typos

      - name: Run typos
        run: typos