[default.extend-words]
Hashi = "Hashi"
HashiCorp = "HashiCorp"
MyApp = "MyApp"
OpenAPIv3 = "OpenAPIv3"
AKS = "AKS"

[files]
extend-exclude = [
  "**/.*",
  "**/.**",
  "./**",
  "./docs/**",
  "./docs/*",
  ".README.md",
  "venv/*",
  ".env.local",
  ".gitignore",
  "mkdocs.yml",
  "requirements.txt"
]